name: Call a reusable workflow
on:
  workflow_dispatch:  
jobs:
  call-workflow-passing-mona:
    uses: Elapeine/TestAzDeploy/.github/workflows/worflow-1.yml@main
    with:
      username: mona
   # secrets:
   #   token: ${{ secrets.TOKEN }}
   
  call-workflow-passing-eric:
    uses: Elapeine/TestAzDeploy/.github/workflows/worflow-1.yml@main
    with:
      username: eric
   # secrets:
   #   token: ${{ secrets.TOKEN }}

