name: Call a reusable workflow
on:
  workflow_dispatch:  
env:
      DAY_OF_WEEK: Mon
jobs:
  call-workflow-passing-mona:
    name: Job 1
    uses: Elapeine/TestAzDeploy/.github/workflows/workflow-1.yml@main
    with:
      username: mona
   # secrets:
   #   token: ${{ secrets.TOKEN }}
   
  call-workflow-passing-eric:
   name: Job 2
   needs: call-workflow-passing-mona
   uses: Elapeine/TestAzDeploy/.github/workflows/workflow-1.yml@main
   with:
     username: eric
   # secrets:
   #   token: ${{ secrets.TOKEN }}
   
  otherjob: 
   needs: call-workflow-passing-eric
   name: other job
    # The type of runner that the job will run on
   runs-on: ubuntu-latest
   steps:
      - name: "display "
        run: echo ok =  "${{ env.action_state }}"

