name: Master Call a reusable workflow

on:
  pull_request:
    branches:
      - main

jobs:

  call-workflow-passing-data:
    uses: Elapeine/TestAzDeploy/.github/workflows/worflow-1.yml.yml@main
    with:
      username: mona
   # secrets:
   #   token: ${{ secrets.TOKEN }}
