name: Call a reusable workflow
on:
  workflow_dispatch:  
jobs:
  call-workflow-passing-data:
    uses: Elapeine/TestAzDeploy/.github/workflows/worflow-1.yml@main
    with:
      username: mona
   # secrets:
   #   token: ${{ secrets.TOKEN }}
